biz:
  sched_server: "192.168.36.102:30080" #"localhost:80" # "192.168.32.13:80" # node_manager 使用
  first_party: true  # node_manager 使用,  first_party 表示是否为自营 。 如果不填写默认为 false

depend:
  mysql_dsn: "root:gzn%zkTJ8x!gGZO6@tcp(192.168.31.28:3306)/biz?charset=utf8mb4&parseTime=True&loc=Local" # server 使用
  mq_dsn: "amqp://guest:guest@192.168.31.28:5672" # server 使用
  minio_dsn: "admin:password@192.168.36.102:32000" # node_manager 使用 (仅配套 first_party 为true时 使用)

debug:
  biz_log_level: 6
  # 0. PanicLevel; 1. FatalLevel; 2. ErrorLevel; 3. WarnLevel; 4. InfoLevel; 5. DebugLevel; 6. TraceLevel
  sql_log_level: 3
  # 1. Silent ; 2. Error ; 3. Warn ; 4. Info ;
  #auth_disabled: false
  debug_mode: true
  log_server: "192.168.36.101:5000"
