depend:
  mysql_dsn_biz: "root:gzn%zkTJ8x!gGZO6@tcp(192.168.31.6:3306)/biz?charset=utf8mb4&parseTime=True&loc=Local"

debug:
  biz_log_level: 6
  # 0. PanicLevel; 1. FatalLevel; 2. ErrorLevel; 3. WarnLevel; 4. InfoLevel; 5. DebugLevel; 6. TraceLevel
  sql_log_level: 3
  # 1. Silent ; 2. Error ; 3. Warn ; 4. Info ;
  #auth_disabled: false
  debug_mode: true